Mutation:
  type: object
  config:
    fields:
      CreateOrUpdateApartment:
        builder: "Relay::Mutation"
        builderConfig:
          inputType: ApartmentInput
          payloadType: CreateOrUpdateApartmentPayload
          mutateAndGetPayload: "@=mutation('createOrUpdateApartment', [value['streetAddress'], value['apartmentId']])"

# config/graphql/types/UpdateUserProfilePayload.type.yaml
CreateOrUpdateApartmentPayload:
  type: relay-mutation-payload
  config:
    fields:
      # Add all needed fields for the payload depending on your business logic
      street_address:
        type: 'String!'
      id:
        type: 'Int'